# 通过setting.config获取本配置

name: "yoyo-plugin"
title: "悠悠小助手"
subTitle: "yoyo-plugin (群:882552331)"
version: "1.0.0"

# 图片
imgMaxSize: 5 #上传图片大小限制 MB

# pixiv
hibiAPI: https://hibi.Yunzai-Bot.com
excludeAI: true # 包含AI图片

# 监测PV播放量
PVList:
- BV1Jr421n7n4
- BV1KUopYZEs5

# 指令前缀
rulePrefix:
- ">"
- "›"
- "＞"
- "yy"
- "yoyo"
- "悠悠"
- "寒悠悠"
- "#?蓝原"
- "#?旅谣"
- "#?蓝色星原"
